
export const countries = [
    { name: 'Afghanistan', code: 'AF', prefix: '+93' },
    { name: 'Albania', code: 'AL', prefix: '+355' },
    { name: 'Algeria', code: 'DZ', prefix: '+213' },
    { name: 'Andorra', code: 'AD', prefix: '+376' },
    { name: 'Angola', code: 'AO', prefix: '+244' },
    { name: 'Argentina', code: 'AR', prefix: '+54' },
    { name: 'Armenia', code: 'AM', prefix: '+374' },
    { name: 'Australia', code: 'AU', prefix: '+61' },
    { name: 'Austria', code: 'AT', prefix: '+43' },
    { name: 'Azerbaijan', code: 'AZ', prefix: '+994' },
    { name: 'Bahamas', code: 'BS', prefix: '+1-242' },
    { name: 'Bahrain', code: 'BH', prefix: '+973' },
    { name: 'Bangladesh', code: 'BD', prefix: '+880' },
    { name: 'Belarus', code: 'BY', prefix: '+375' },
    { name: 'Belgium', code: 'BE', prefix: '+32' },
    { name: 'Bolivia', code: 'BO', prefix: '+591' },
    { name: 'Brazil', code: 'BR', prefix: '+55' },
    { name: 'Bulgaria', code: 'BG', prefix: '+359' },
    { name: 'Cambodia', code: 'KH', prefix: '+855' },
    { name: 'Cameroon', code: 'CM', prefix: '+237' },
    { name: 'Canada', code: 'CA', prefix: '+1' },
    { name: 'Chile', code: 'CL', prefix: '+56' },
    { name: 'China', code: 'CN', prefix: '+86' },
    { name: 'Colombia', code: 'CO', prefix: '+57' },
    { name: 'Costa Rica', code: 'CR', prefix: '+506' },
    { name: 'Croatia', code: 'HR', prefix: '+385' },
    { name: 'Cuba', code: 'CU', prefix: '+53' },
    { name: 'Cyprus', code: 'CY', prefix: '+357' },
    { name: 'Czech Republic', code: 'CZ', prefix: '+420' },
    { name: 'Denmark', code: 'DK', prefix: '+45' },
    { name: 'Dominican Republic', code: 'DO', prefix: '+1-809' },
    { name: 'Ecuador', code: 'EC', prefix: '+593' },
    { name: 'Egypt', code: 'EG', prefix: '+20' },
    { name: 'Estonia', code: 'EE', prefix: '+372' },
    { name: 'Finland', code: 'FI', prefix: '+358' },
    { name: 'France', code: 'FR', prefix: '+33' },
    { name: 'Georgia', code: 'GE', prefix: '+995' },
    { name: 'Germany', code: 'DE', prefix: '+49' },
    { name: 'Ghana', code: 'GH', prefix: '+233' },
    { name: 'Greece', code: 'GR', prefix: '+30' },
    { name: 'Hungary', code: 'HU', prefix: '+36' },
    { name: 'Iceland', code: 'IS', prefix: '+354' },
    { name: 'India', code: 'IN', prefix: '+91' },
    { name: 'Indonesia', code: 'ID', prefix: '+62' },
    { name: 'Iran', code: 'IR', prefix: '+98' },
    { name: 'Iraq', code: 'IQ', prefix: '+964' },
    { name: 'Ireland', code: 'IE', prefix: '+353' },
    { name: 'Israel', code: 'IL', prefix: '+972' },
    { name: 'Italy', code: 'IT', prefix: '+39' },
    { name: 'Jamaica', code: 'JM', prefix: '+1-876' },
    { name: 'Japan', code: 'JP', prefix: '+81' },
    { name: 'Jordan', code: 'JO', prefix: '+962' },
    { name: 'Kazakhstan', code: 'KZ', prefix: '+7' },
    { name: 'Kenya', code: 'KE', prefix: '+254' },
    { name: 'Kuwait', code: 'KW', prefix: '+965' },
    { name: 'Latvia', code: 'LV', prefix: '+371' },
    { name: 'Lebanon', code: 'LB', prefix: '+961' },
    { name: 'Libya', code: 'LY', prefix: '+218' },
    { name: 'Lithuania', code: 'LT', prefix: '+370' },
    { name: 'Luxembourg', code: 'LU', prefix: '+352' },
    { name: 'Malaysia', code: 'MY', prefix: '+60' },
    { name: 'Mexico', code: 'MX', prefix: '+52' },
    { name: 'Morocco', code: 'MA', prefix: '+212' },
    { name: 'Netherlands', code: 'NL', prefix: '+31' },
    { name: 'New Zealand', code: 'NZ', prefix: '+64' },
    { name: 'Nigeria', code: 'NG', prefix: '+234' },
    { name: 'Norway', code: 'NO', prefix: '+47' },
    { name: 'Oman', code: 'OM', prefix: '+968' },
    { name: 'Pakistan', code: 'PK', prefix: '+92' },
    { name: 'Peru', code: 'PE', prefix: '+51' },
    { name: 'Philippines', code: 'PH', prefix: '+63' },
    { name: 'Poland', code: 'PL', prefix: '+48' },
    { name: 'Portugal', code: 'PT', prefix: '+351' },
    { name: 'Qatar', code: 'QA', prefix: '+974' },
    { name: 'Romania', code: 'RO', prefix: '+40' },
    { name: 'Russia', code: 'RU', prefix: '+7' },
    { name: 'Saudi Arabia', code: 'SA', prefix: '+966' },
    { name: 'Senegal', code: 'SN', prefix: '+221' },
    { name: 'Serbia', code: 'RS', prefix: '+381' },
    { name: 'Singapore', code: 'SG', prefix: '+65' },
    { name: 'Slovakia', code: 'SK', prefix: '+421' },
    { name: 'Slovenia', code: 'SI', prefix: '+386' },
    { name: 'South Africa', code: 'ZA', prefix: '+27' },
    { name: 'South Korea', code: 'KR', prefix: '+82' },
    { name: 'Spain', code: 'ES', prefix: '+34' },
    { name: 'Sweden', code: 'SE', prefix: '+46' },
    { name: 'Switzerland', code: 'CH', prefix: '+41' },
    { name: 'Syria', code: 'SY', prefix: '+963' },
    { name: 'Taiwan', code: 'TW', prefix: '+886' },
    { name: 'Thailand', code: 'TH', prefix: '+66' },
    { name: 'Tunisia', code: 'TN', prefix: '+216' },
    { name: 'Turkey', code: 'TR', prefix: '+90' },
    { name: 'Uganda', code: 'UG', prefix: '+256' },
    { name: 'Ukraine', code: 'UA', prefix: '+380' },
    { name: 'United Arab Emirates', code: 'AE', prefix: '+971' },
    { name: 'United Kingdom', code: 'GB', prefix: '+44' },
    { name: 'United States', code: 'US', prefix: '+1' },
    { name: 'Uruguay', code: 'UY', prefix: '+598' },
    { name: 'Venezuela', code: 'VE', prefix: '+58' },
    { name: 'Vietnam', code: 'VN', prefix: '+84' },
    { name: 'Yemen', code: 'YE', prefix: '+967' },
    { name: 'Zambia', code: 'ZM', prefix: '+260' },
    { name: 'Zimbabwe', code: 'ZW', prefix: '+263' },
  ];
